#!/bin/bash
# Inner pages: Saltwave chrome (bootstrap + common + home-style) with our
# content styles loaded last so they win. index.html is NOT built here —
# it is generated by port.mjs from the Saltwave templates.
set -e
cd "$(dirname "$0")"
SITE="https://trendwalkers.dpdns.org"
for f in _src/body-*.html; do
  page="$(basename "${f#_src/body-}")"
  title=$(sed -n '1s/^<!--title:\(.*\)-->$/\1/p' "$f")
  desc=$(sed -n  '2s/^<!--desc:\(.*\)-->$/\1/p'  "$f")
  canon=$(sed -n '3s/^<!--canon:\(.*\)-->$/\1/p' "$f")
  [ -n "$title" ] && [ -n "$desc" ] && [ -n "$canon" ] || { echo "MISSING META in $f"; exit 1; }
  {
    echo '<!doctype html>'
    echo '<html lang="en">'
    echo '    <head>'
    echo '        <meta charset="utf-8">'
    echo '        <meta name="viewport" content="width=device-width, initial-scale=1">'
    echo '        <link rel="icon" type="image/svg+xml" href="/favicon.svg">'
    echo "        <title>${title}</title>"
    echo "        <meta name=\"description\" content=\"${desc}\">"
    echo "        <link rel=\"canonical\" href=\"${SITE}${canon}\">"
    echo "        <meta property=\"og:title\" content=\"${title}\">"
    echo "        <meta property=\"og:description\" content=\"${desc}\">"
    echo '        <meta property="og:type" content="website">'
    echo "        <meta property=\"og:url\" content=\"${SITE}${canon}\">"
    echo "        <meta property=\"og:image\" content=\"${SITE}/logo.svg\">"
    echo '        <meta name="twitter:card" content="summary_large_image">'
    cat _src/_chrome-head.part
    echo '        <link rel="stylesheet" href="/style.css">'
    cat _src/_schema.part
    echo '    </head>'
    echo '    <body class="page-body inner-page">'
    cat _src/_header.part
    echo '<main>'
    tail -n +4 "$f"
    echo '</main>'
    cat _src/_footer.part
    echo '    </body>'
    echo '</html>'
  } > "$page"
done
echo "built: $(ls -1 _src/body-*.html | sed 's|_src/body-||' | tr '\n' ' ')"
